### PR TITLE
Ucsf updates

### PR DESCRIPTION
**Pull request by hehinson**

### CODE REVIEW

**Comment by ericearl** [comment]
@hehinson Thanks for the PR! Did you mean to do this to your fork instead?

**Review by hehinson — COMMENTED** [review]
> @hehinson Thanks for the PR! Did you mean to do this to your fork instead? 

Oh I sure did. My apologies--getting back into Github after a long absence.

**Comment by ericearl** [comment]
Not a problem @hehinson! Have you seen our wealth of old presentations here? https://osf.io/qcyhu/ Enjoy and good luck! I'm, happy people are still using this.

**Comment by hehinson** [comment]
Thank you for this! I have forgotten how to publish to my fork, so I need this!
H.E.

H.E. Hinson, MD MCR FAAN FNCS
Professor of Clinical Neurology, Department of Neurology
University of California, San Francisco
Zuckerberg San Francisco General Hospital
Box 0896
2540 – 23rd Street, Floor 5
San Francisco, CA 94110| Email: ***@***.******@***.***> | Pronouns: she/her
https://hinsonlab.ucsf.edu/
_________________________________________________

                                                              [rgf8H7bnjPT17hV0AAAAASUVORK5CYIIA]


From: Eric Earl ***@***.***>
Date: Thursday, September 19, 2024 at 2:36 PM
To: BioData-Club/jekyll-academic ***@***.***>
Cc: Hinson, H E ***@***.***>, Mention ***@***.***>
Subject: Re: [BioData-Club/jekyll-academic] Ucsf updates (PR #2)
Not a problem @hehinson! Have you seen our wealth of old presentations here? https: //osf. io/qcyhu/ Enjoy and good luck! I'm, happy people are still using this. — Reply to this email directly, view it on GitHub, or unsubscribe. You are
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

Not a problem @hehinson<https://urldefense.com/v3/__https:/github.com/hehinson__;!!LQC6Cpwp!ogakESv4k2YyTcpmQo5iNk--Korro0EPU27w_hQdSMFR6xXKYE_EPXgHLhlaIfSe9M_U27T4pPJ_ANGZI2laor-pkw$>! Have you seen our wealth of old presentations here? https://osf.io/qcyhu/<https://urldefense.com/v3/__https:/osf.io/qcyhu/__;!!LQC6Cpwp!ogakESv4k2YyTcpmQo5iNk--Korro0EPU27w_hQdSMFR6xXKYE_EPXgHLhlaIfSe9M_U27T4pPJ_ANGZI2k3QCmLdg$> Enjoy and good luck! I'm, happy people are still using this.

**Pull request closed without merging**
